### ISSUE TITLE
Style "Login With Shibboleth" Button

### ISSUE THREAD

**Issue by michaelryanmcneill** [michaelryanmcneill/shibboleth#12]
It would be good to style the "Login With Shibboleth" button to look like a button instead of just a randomly placed link. I'd like to style it the same (or similar) to Jetpack's "Login with WordPress.com" option (see example).
![maxresdefault](https://user-images.githubusercontent.com/1049010/30224495-0e5acdc2-949d-11e7-993b-1e5d90028ab3.jpg)

**Comment by jrchamp** [comment]
Being able to style it would be nice. Right now, I'm overriding the default language file to change the text and inject an image...

**Comment by michaelryanmcneill** [comment]
When you say an image @jrchamp, do you mean like a font awesome icon or an actual image? I think it would be worthwhile to offer a customizable button in the options menu. I'm thinking text and color, but possibly including an image maybe would be a benefit for users.

**Comment by jrchamp** [comment]
I put an `img` tag into the language file so I could direct our users a bit more easily to the "right" login link. Really, as long as there's a CSS `class` or `id` for me to target, I can make it work. If you want to make it easier than that, I'll definitely be on board. Would be thrilled to not have to look up how to rebuild a po/mo.

**Comment by michaelryanmcneill** [comment]
This has been completed. It will be released with the next version. I included a span with a class of `shibboleth-icon` to target for images. The button itself has customizable text via the options page and has a class of `shibboleth-button`. It looks like this: 
<img width="1440" alt="screen shot 2017-09-16 at 7 01 17 pm" src="https://user-images.githubusercontent.com/1049010/30516593-79b23928-9b11-11e7-9151-1446006a11a2.png">
