### ISSUE TITLE
Missing issues from previous repo.

### ISSUE THREAD

**Issue by ghost** [michaelryanmcneill/shibboleth#15]
Hello,

I never did it myself but maybe there was a way to transfer the ownership (and keeping valuable issue history / documentation) without moving to a new fork?

**Comment by michaelryanmcneill** [comment]
Unfortunately, I wasn't able to take over control of that repository. And unfortunately, forking comes with some specific restrictions that are imposed by GitHub, which is why this is a standalone repository (although this includes the commit history from the previous repository).
