### ISSUE TITLE
Option for custom prefix other than REDIRECT_

### ISSUE THREAD

**Issue by dellch** [michaelryanmcneill/shibboleth#27]
Our service provider adds an additional prefix (specifically `UFShib_`, in this situation), so in my case the entire prefix is `REDIRECT_UFShib_`.

Been using your plugin for a while and have always just edited the .php, but a textbox would be nice.  I might be able to help w/ this sometime in the next month, but let me know your thoughts on the best way to incorporate this.  (Override the dropdown list and hand input the prefix in a textbox? some other way?)

**Comment by jrchamp** [comment]
If UFShib_ is always present, wouldn't this just be in the textbox that's already present for each field?

**Comment by michaelryanmcneill** [comment]
I agree with @jrchamp here, I'm not sure why the existing text box for the attributes isn't sufficient. Can you provide additional details if that doesn't solve your issue?

**Comment by dellch** [comment]
Shib_Session_ID also needs the prefix

**Comment by michaelryanmcneill** [comment]
Ah, that does make sense. I'll target this for 2.1 and if you can spend some time making a PR, that'd be great. I'd like to add a "Custom" prefix option and have a hidden text field that appears when the "Custom" prefix option is selected in the dropdown.

**Comment by jrchamp** [comment]
How are you modifying the Shib-Session-ID parameter? That's supposedly [hardwired](https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAttributeAccess). If these can be (now or in the future) customized, it may be better to add a text box to specify this value.

**Comment by michaelryanmcneill** [comment]
Taking a shot in the dark, I'm guessing that whatever is redirecting the attribute (`REDIRECT_`) is adding the additional prefix.

**Comment by dellch** [comment]
I think @michaelryanmcneill is right, although I'm not involved in the Identity provider of our organization, but I think they chose to do it because legacy web applications used similar variable/header names for so they prefixed with UFShib_ to show that the shibboleth provider was vending.

**Comment by michaelryanmcneill** [comment]
This should be resolved by 18ee3c7.
