### ISSUE TITLE
401 Authorization Required error after upgrade from 1.8.1 to 2.0.2, revert doesn't fix

### ISSUE THREAD

**Issue by scott8035** [michaelryanmcneill/shibboleth#30]
Hi all. I'm working with a new client who set up a dev box for me with Shibboleth 1.8.1 installed. Everything worked. I backed everything up with All In One WP Migration, then updated Shibboleth to current (2.0.2). Now I get a 401 Authorization Required error for both front- and back-ends.

I restored the original 1.8.1 version, but it has no impact on the error. Unfortunately, I need a working version of wordpress to use the All In One WP Migration plugin to do a recovery...and now I can't.

Any ideas how to get out of this mess?

![image](https://user-images.githubusercontent.com/4405585/35307872-a385da98-006a-11e8-9f6f-1db13a6a8885.png)

**Comment by jrchamp** [comment]
Perhaps the .htaccess file was updated.

**Comment by scott8035** [comment]
You are indeed correct. I commented out the lines related to Shibboleth
auth and everything is working fine. Thank you!

---scott

Contact info: scott8035@gmail.com | 414-469-8241 | LinkedIn
<http://www.linkedin.com/in/scottthomason>

**Comment by jrchamp** [comment]
@scott8035 The normal .htaccess changes are not supposed to prevent access. It should be these two lines:
```
AuthType shibboleth
Require shibboleth
```

If it is those two, I wonder if this would fix the issue:
```
AuthType shibboleth
ShibRequestSetting requireSession false
Require shibboleth
```

If it is not those two, could you provide the lines that you commented?

**Comment by michaelryanmcneill** [comment]
Thanks for your help on this one @jrchamp!

**Comment by scott8035** [comment]
Sorry for the delay. Yes, it was the AuthType and Require lines like you
say. Commented those out and now I'm Shibboleth-free for the moment. Thank
you!

---scott

Contact info: scott8035@gmail.com | 414-469-8241 | LinkedIn
<http://www.linkedin.com/in/scottthomason>
