### ISSUE TITLE
Blank shibboleth_default_role prevents login when shibboleth_create_accounts is enabled

### ISSUE THREAD

**Issue by jrchamp** [michaelryanmcneill/shibboleth#36]
Issue #22 added a blank default role option so that automatically created users are not automatically given a role in the system. Unfortunately, when ``shibboleth_default_role`` is blank and  ``shibboleth_create_accounts`` is enabled, no user can log in even if they already have an existing account and existing roles. We discussed this in the previous issue and the idea of a fake role value was proposed. Where that would be the simple answer, I'd prefer if we could continue to use the blank value and handle it appropriately in the rest of the code.

**Comment by michaelryanmcneill** [comment]
Thanks @jrchamp! I'll get working on this when I get some free time, but if you have sometime to PR a solution, that'd be great!

**Comment by jrchamp** [comment]
I took a look and I think I got it. One second.
