### ISSUE TITLE
Pot file not up to date + french

### ISSUE THREAD

**Issue by ghost** [michaelryanmcneill/shibboleth#41]
It's very minor. I think the pot file is not up to date.

I see the new login with Shibboleth button but the section title is displaying as "**Or**" (esc_html_e( 'Or', 'shibboleth' )) in our french screen but the string is not in the pot file.

I can surely help with the french translation  (at least the few front-end text that I will have to fix anyway).

From the WordPress screen it looks like the plugin is not fully ready for WordPress translation? https://translate.wordpress.org/locale/fr-ca/default/wp-plugins/shibboleth

Where you planning to just add translation in Git repo?

**Comment by jrchamp** [comment]
I'm not exactly sure, but based on the error in the WordPress Slack, #42 should allow translate.wordpress.org to work.

**Comment by ghost** [comment]
I will close the issue. I took a note on my side to follow up.

**Comment by jrchamp** [comment]
@eric-gagnon The Shibboleth plugin is now ready for translate.wordpress.org! https://translate.wordpress.org/locale/fr-ca/default/wp-plugins/shibboleth

**Comment by ghost** [comment]
Thanks! I will give a try to just translating the front-facing string that was a, very minor, trouble for us and see if I can give a try to completing a first base for all the other strings (admin config).

**Comment by ghost** [comment]
It looks like there is a approval needed but I'm still new to WordPress translation I'm not sure who need to do it (plugin maintainer ou the fr-CA group).

I'll see if I can be granted the rights.

**Comment by ghost** [comment]
Ok. I have gone to polyglot channel on WP slack. I'll keep you updated.
I have installed the latest Shibboleth plugin in our dev environnement for testing, thanks for the update.

**Comment by ghost** [comment]
I have been granted editor rights for fr_CA. The package is only released if there is 95% approved string, so I will do this on a slower track and probably on my own time (the front-end issue was really just with the "or" text!).
