### ISSUE TITLE
2.1 disables automatic login via Shib

### ISSUE THREAD

**Issue by trandrew** [michaelryanmcneill/shibboleth#48]
Updated to 2.1 and it unchecked the Default Login Method. When trying to recheck the box and save, the box doesn't save.

Browser console gives me this error when I try to save: 
`Failed to set referrer policy: The value '' is not one of 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-cross-origin', 'same-origin', 'strict-origin', 'strict-origin-when-cross-origin', or 'unsafe-url'. The referrer policy has been left unchanged.`

**Comment by michaelryanmcneill** [comment]
This is strange. That looks like a CORS issue and not related to the plugin, but I will investigate shortly. Thanks for reporting.

**Comment by trandrew** [comment]
Just to add, I reverted back to 2.0.2 and the option saving worked fine again.

**Comment by michaelryanmcneill** [comment]
Thanks for that additional info. Do other options present the same problem or just that option? If so, I believe I know the problem and can fix it rather easily in a dot release.

**Comment by trandrew** [comment]
I only tried that option when I had 2.1 installed. I can test 2.1 again but would rather wait until after the work day (pacific timezone). 

Also I forgot to mention that the option wouldn't save in the dashboard settings, but eventually my wp-login.php pages eventually automatically went to the Shibboleth login screen. However it would only work for the non-mapped-domain URLs (on a multisite setup). I'll try to get more details about this error once I try the new release / new dot release again.

**Comment by michaelryanmcneill** [comment]
I believe I've gotten this issue resolved. I don't believe the impact was that large, but I'm going to go ahead and push out 2.1.1.
