### ISSUE TITLE
Shibboleth login form has wrong url when in frontend

### ISSUE THREAD

**Issue by Alhrath** [michaelryanmcneill/shibboleth#52]
On some websites, the theme display a login form in the frontend. When it's the case, the shibboleth_login_form function will display an incorrect link to shibboleth login (actual_page_url?action=shibboleth) that will fail to redirect the user.

I fixed this by changing the first line of the function (line 864) to : 
`global $wp; $login_url = add_query_arg( 'action', 'shibboleth', wp_login_url( home_url( $wp->request ) ) );`
This way, the user will be redirected correctly to shibboleth auth page, then redirected back to the original page.

Is it possible to implement this feature in the next release ? I'm currently using last version (2.1.1).

**Comment by michaelryanmcneill** [comment]
If you could provide me a way to reproduce this, I'd really appreciate it. Also, please add your code into a PR and I'll review it.

**Comment by Alhrath** [comment]
Unfortunately, the situation I came across involve a paid theme, [Jupiter](https://themeforest.net/item/jupiter-multipurpose-responsive-theme/5177775), so I cannot provide a full reproducible method, but here is the code part that cause the problem : 



<div class="mk-header-login">
    <a href="#" id="mk-header-login-button" class="mk-login-link mk-toggle-trigger"><?php //Mk_SVG_Icons::get_svg_icon_by_class_name(true, 'mk-moon-user-8', 16); ?><?php _e('FORS Intranet', 'jupiter-fors');?></a>
	<div class="mk-login-register mk-box-to-trigger">

		<div id="mk-login-panel">
				<form id="mk_login_form" name="mk_login_form" method="post" class="mk-login-form" action="<?php echo site_url('wp-login.php', 'login_post')?>">
					<span class="form-section">
					<label for="log"><?php _e('Username', 'mk_framework');?></label>
					<input type="text" id="username" name="log" class="text-input">
					</span>
					<span class="form-section">
						<label for="pwd"><?php _e('Password', 'mk_framework');?></label>
						<input type="password" id="password" name="pwd" class="text-input">
					</span>
						<?php do_action('login_form');?>
					<label class="mk-login-remember">
						<input type="checkbox" name="rememberme" id="rememberme" value="forever"><?php _e(" Remember Me", 'mk_framework');?>
					</label>

					<input type="submit" id="login" name="submit_button" class="accent-bg-color button" value="<?php _e("LOG IN", 'mk_framework');?>">
						<?php wp_nonce_field('ajax-login-nonce', 'security');?>

					<div class="register-login-links">
							<a href="#" class="mk-forget-password"><?php _e("Forgot?", 'mk_framework');?></a>
						<?php if (get_option('users_can_register')) {?>
							<a href="#" class="mk-create-account"><?php _e("Register", 'mk_framework');?></a>
						<?php }?>
						</div>
					<div class="clearboth"></div>
					<p class="mk-login-status"></p>
				</form>
		</div>

						<?php if (get_option('users_can_register')) {?>
			<div id="mk-register-panel">
					<div class="mk-login-title"><?php _e("Create Account", 'mk_framework');?></div>

					<form id="register_form" name="login_form" method="post" class="mk-form-regsiter" action="<?php echo site_url('wp-login.php?action=register', 'login_post')?>">
						<span class="form-section">
							<label for="log"><?php _e('Username', 'mk_framework');?></label>
							<input type="text" id="reg-username" name="user_login" class="text-input">
						</span>
						<span class="form-section">
							<label for="user_email"><?php _e('Your email', 'mk_framework');?></label>
							<input type="text" id="reg-email" name="user_email" class="text-input">
						</span>
						<span class="form-section">
							<input type="submit" id="signup" name="submit" class="accent-bg-color button" value="<?php _e("Create Account", 'mk_framework');?>">
						</span>
						<?php do_action('register_form');?>
						<input type="hidden" name="user-cookie" value="1" />
						<input type="hidden" name="redirect_to" value="<?php echo $current_url;?>?register=true" />
						<div class="register-login-links">
							<a class="mk-return-login" href="#"><?php _e("Already have an account?", 'mk_framework');?></a>
						</div>
					</form>
			</div>
						<?php }?>

		<div class="mk-forget-panel">
				<span class="mk-login-title"><?php _e("Forget your password?", 'mk_framework');?></span>
				<form id="forgot_form" name="login_form" method="post" class="mk-forget-password-form" action="<?php echo site_url('wp-login.php?action=lostpassword', 'login_post')?>">
					<span class="form-section">
							<label for="user_login"><?php _e('Username or E-mail', 'mk_framework');?></label>
						<input type="text" id="forgot-email" name="user_login" class="text-input">
					</span>
					<span class="form-section">
						<input type="submit" id="recover" name="submit" class="accent-bg-color button" value="<?php _e("Get New Password", 'mk_framework');?>">
					</span>
					<div class="register-login-links">
						<a class="mk-return-login" href="#"><?php _e("Remembered Password?", 'mk_framework');?></a>
					</div>
				</form>

		</div>
	</div>
</div>
`

This code is displayed in a submenu but you should be able to display it anywhere outside the login page for testing. I sent you a PR with my fix : #53

**Comment by michaelryanmcneill** [comment]
This is resolved by #53 which will be included with 2.2. Sorry for the delay.
