### ISSUE TITLE
Supported WordPress versions

### ISSUE THREAD

**Issue by dandalpiaz** [michaelryanmcneill/shibboleth#62]
The most recent version of the plugin lists the "Tested up to" value as 4.9.14. I don't know if there are specific test criteria that need to be met, but I can vouch that the plugin has been working well for me on several single-site installs through multiple major versions of WordPress 5.x. 

If there are specific test cases that need to be run in order to increment this value, let me know and I'd be happy to help if I can. 

The thing that prompted me to look at this was the Wordfence security plugin which has started flagging the Shibboleth plugin as 'possibly abandoned'. I think it will do so for any plugin that hasn't received an update over a two year period.

**Comment by jrchamp** [comment]
This is likely coming from the readme.txt file: https://github.com/michaelryanmcneill/shibboleth/blob/a7ccb3e4aff7afda3e71d92d613c20962b1bb830/readme.txt#L5

I haven't seen @michaelryanmcneill in a bit, but I know it's been a busy time for a lot of us.

**Comment by jmdemuth** [comment]
> 
> 
> The most recent version of the plugin lists the "Tested up to" value as 4.9.14. I don't know if there are specific test criteria that need to be met, but I can vouch that the plugin has been working well for me on several single-site installs through multiple major versions of WordPress 5.x.
> 
> If there are specific test cases that need to be run in order to increment this value, let me know and I'd be happy to help if I can.
> 
> The thing that prompted me to look at this was the Wordfence security plugin which has started flagging the Shibboleth plugin as 'possibly abandoned'. I think it will do so for any plugin that hasn't received an update over a two year period.

I can confirm that it seems to work well under v5.x, but it would be very reassuring to see something "official" from the developers.  Thanks.

**Comment by michaelryanmcneill** [comment]
Hi all, primary developer here! Sorry for the lack of updates or maintenance around the Shibboleth plugin. I plan to devote some time next week to getting things updated (including increasing the tested up to tag). I do not have access to a Shibboleth IdP anymore to test, but I'll try to deploy one to my local OpenShift environment to test with.

**Comment by michaelryanmcneill** [comment]
My apologies again on the delay. I am working to get 2.2 out today. I will work to keep things updated in the future. Closing this out as it was addressed in 05b3e70.
