### ISSUE TITLE
Non visible Images on Safari 

### ISSUE THREAD

**Issue by Thommy-ja** [michaelryanmcneill/shibboleth#84]
Images are not visible in Safari Browser after Plugin activation.

**Comment by jrchamp** [comment]
I don't have Safari, can you please provide an image that shows the problem?

**Comment by Thommy-ja** [comment]
This is our side how it should look like : 
![Bildschirmfoto 2022-07-30 um 14 48 28](https://user-images.githubusercontent.com/66822196/181915084-e7919344-00c9-475a-a3d8-5c4e5bbd4464.png)

And this after activation of the Plugin and Login into our Shibboleth: 
![Bildschirmfoto 2022-07-30 um 14 49 28](https://user-images.githubusercontent.com/66822196/181915108-fa5d00fc-f788-4470-bdce-30ab4f7b443a.png)

It only happens with the Safari browser.

**Comment by jrchamp** [comment]
The two explanations that I can think of are that the server is responding with a different response when those images are requested while the plugin is active.

Are the image URLs changing? Or can you see the HTTP responses in Safari?

**Comment by Thommy-ja** [comment]
Yes the Image URL's are changing after the plugin activation.

**Comment by jrchamp** [comment]
What is the difference between the two URLs? It's okay to anonymize the hostname if it is private.

**Comment by Thommy-ja** [comment]
The URL changes for example from 
'https://chelm.uni-saarland.de/wp-content/uploads/2022/05/ausfuehrlich-173x95.png'
to
'https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_768/https://chelm.uni-saarland.de/wp-content/uploads/2022/05/ausfuehrlich-768x424.png'

**Comment by michaelryanmcneill** [comment]
Are you using the AutoOptimize plugin or similar plugin that does image optimization? ShortPixel is not something the plugin uses or attempts to use. Have you tried disabling all plugins and trying to login?

**Comment by Thommy-ja** [comment]
Yes the AutoOptimize was the problem. Thank you !
