### ISSUE TITLE
Session Error with WP 6.0.2

### ISSUE THREAD

**Issue by heikoweier** [michaelryanmcneill/shibboleth#87]
We use WP Multisite and use the plugin "Multisite Language Swicher" to link two blogs between DE/EN
System is: Ubuntu 20 LTS

We can authenticate successful via shibboleth, an can edit Pages and Articles, but we are no more able to edit the link to the other language. Disabling shibboleth solves the problem.

The  session-errors are with any browser, asnd also in private mode.

Can you help? Is there a Version upgrade for WP 6 Users in sight?

We are getting session errors in /var/log/syslog:

```
Sep 8 14:00:52 vm059 shibboleth: WARN Shibboleth.SessionCache [685915] shib_check_user [default]: client address mismatch, client (xxx.xxx.xxx.59), session (xxx.xxx.xxx.23)

Sep 8 14:00:52 vm059 shibboleth: WARN Shibboleth.ServiceProvider [685915] shib_check_user [default]: error during session lookup: Your IP address (xxx.xxx.xxx.59) does not match the address recorded at the time the session was established.

Sep 8 14:00:54 vm059 shibboleth: ERROR Shibboleth.Listener [685935] shib_check_user [default]: remoted message returned an error: Your session is not available in the session store, and you must re-authenticate.

Sep 8 14:00:54 vm059 shibboleth: WARN Shibboleth.ServiceProvider [685935] shib_check_user [default]: error during session lookup: Your session is not available in the session store, and you must re-authenticate.
```

**Comment by jrchamp** [comment]
Hi @heikoweier 

What is the link to the other language when the Shibboleth plugin is enabled? My initial guess is that you might be having the same issue as #86 

The syslog errors appear to be unrelated (they are shibd errors, not WordPress plugin errors).

**Comment by heikoweier** [comment]
Hi @jrchamp,
WP Multisite is organized with subdirectories. So we have the german language in the root / and the english in /en/
I will try your suggestion from #86 

Heiko

**Comment by heikoweier** [comment]
Sorry, the code change from #86 did not solve the problem.
The shibd error comes exact, when i try to save the link to the other blog.

Heiko

**Comment by tzeumer** [comment]
Hi,
although we didn't change anything, something else became a configuration problem. It is solved and does not seem to be related directly with the plugin. This ticket can be closed. Thank you very much.
