### ISSUE TITLE
NGINX not passing Shibboleth session variables in header

### ISSUE THREAD

**Issue by NchemIcaLS** [michaelryanmcneill/shibboleth#9]
I have an issue that may not pertain directly to this plugin but was wondering if anyone could help me out.

I want to use this plugin but I am serving my website via NGINX. I have compiled NGINX with the required modules ([nginx-http-shibboleth](https://github.com/nginx-shib/nginx-http-shibboleth)) and it connects to the Shibboleth provider. I am able to generate a session, login and logout. The problem is that the plugin is not able to take the session variables and create an account. Instead when I attempt to login it always loops back to the shibboleth authentication.

I think the problem is that NGINX does not pass the Shibboleth session variables in the header. The reason I believe this is when I var_dump $_SERVER in php it does not contain any Shibboleth data. Does anyone have any tips on how I could do this or debug this further? I am happy to post any config files or logs if needed.

[X-Post](https://github.com/nginx-shib/nginx-http-shibboleth/issues/27)

**Comment by michaelryanmcneill** [comment]
@NchemIcaLS, thanks for your issue submission and your cross post to nginx-shib/nginx-http-shibboleth. I am going to try and reproduce this in a local development environment, but that is going to take some time. I'll get back to you when I have additional details.

**Comment by michaelryanmcneill** [comment]
So, after looking a little closer at your cross posting, this is a small difference I noticed from the [configuration example](https://github.com/nginx-shib/nginx-http-shibboleth#configuration):

Your nginx.conf:

```
location /secure {
       shib_request /shibauthorizer;
       include snippets/shib_fastcgi_params;

       fastcgi_pass unix:/run/php/php7.0-fpm.sock;
}
```

The example nginx.conf:

```
location /secure-environment-vars {
    shib_request /shibauthorizer;
    include shib_fastcgi_params;
    shib_request_set $shib_commonname $upstream_http_variable_commonname;
    shib_request_set $shib_email $upstream_http_variable_email;
    fastcgi_param COMMONNAME $shib_commonname;
    fastcgi_param EMAIL $shib_email;
    fastcgi_pass unix:/path/to/backend.socket;
}
```

Note the difference on the `include`. You're including `shib_fastcgi_params` from snippets, whereas, in the example, they're not using the snippets subdirectory. Please try that and let me know the results of your test.

**Comment by NchemIcaLS** [comment]
I tried moving that file and other out of the snippets folder but it did not affect my results. Below is the output when I vardump $_SERVER. In the file shib_fastcgi_params I added a test line for the paramter HTTP_USERNAME with the value NchemIcaLS. This works. What doesn't work is the shib_request_set does not populate the shibboleth variables. You can see below that these are all empty strings.

```
array(51) { ["SERVER_SOFTWARE"]=> string(12) "nginx/1.10.3" ["REQUEST_URI"]=> string(6) "/login" 
["USER"]=> string(8) "www-data" ["HOME"]=> string(8) "/var/www" ["HTTP_COOKIE"]=> string(268) 
"learn_press_user_guest_id=1504527428; _ga=GA1.2.791236528.1504530841; 
PHPSESSID=o456es2e536fp02cp9lhivpab0; wordpress_test_cookie=WP+Cookie+check; 
_shibsession_64656661756c7468747470733a2f2f7370682e6574687a2e63682f73686962626f6c657
468=_4510300721196d0972cd1aab9de1f9ff" ["HTTP_UPGRADE_INSECURE_REQUESTS"]=> string(1) 
"1" ["HTTP_ACCEPT_ENCODING"]=> string(17) "gzip, deflate, br" ["HTTP_ACCEPT_LANGUAGE"]=> 
string(14) "en-US,en;q=0.5" ["HTTP_ACCEPT"]=> string(63) 
"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" ["HTTP_USER_AGENT"]=> string(82) 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0" 
["HTTP_HOST"]=> string(11) "(removed)" ["REDIRECT_STATUS"]=> string(3) "200" 
["SERVER_NAME"]=> string(11) "(removed)" ["SERVER_PORT"]=> string(3) "443" 
["SERVER_ADDR"]=> string(14) "(removed)" ["REMOTE_PORT"]=> string(5) "54694" 
["REMOTE_ADDR"]=> string(13) "(removed)" ["GATEWAY_INTERFACE"]=> string(7) "CGI/1.1" 
["HTTPS"]=> string(2) "on" ["SERVER_PROTOCOL"]=> string(8) "HTTP/2.0" ["DOCUMENT_ROOT"]=> 
string(18) "/var/www/wordpress" ["DOCUMENT_URI"]=> string(10) "/index.php" ["SCRIPT_NAME"]=>
 string(10) "/index.php" ["CONTENT_LENGTH"]=> string(0) "" ["CONTENT_TYPE"]=> string(0) "" 
["REQUEST_METHOD"]=> string(3) "GET" ["QUERY_STRING"]=> string(0) "" ["SCRIPT_FILENAME"]=>
 string(28) "/var/www/wordpress/index.php" ["PATH_INFO"]=> string(0) "" ["HTTP_USERNAME"]=> 
string(10) "NchemIcaLS" ["surname"]=> string(0) "" ["studyBranch3"]=> string(0) "" ["persistent-
id"]=> string(0) "" ["mail"]=> string(0) "" ["homeOrganization"]=> string(0) "" ["givenName"]=> 
string(0) "" ["affiliation"]=> string(0) "" ["Remote-User"]=> string(0) "" ["Shib-Session-Index"]=> 
string(0) "" ["Shib-Session-ID"]=> string(0) "" ["Shib-Identity-Provider"]=> string(0) "" ["Shib-
AuthnContext-Decl"]=> string(0) "" ["Shib-AuthnContext-Class"]=> string(0) "" ["Shib-Authentication-
Method"]=> string(0) "" ["Shib-Authentication-Instant"]=> string(0) "" ["Shib-Application-ID"]=> 
string(0) "" ["Auth-Type"]=> string(0) "" ["FCGI_ROLE"]=> string(9) "RESPONDER" ["PHP_SELF"]=> 
string(6) "/login" ["REQUEST_TIME_FLOAT"]=> string(15) "1504940730.8803" ["REQUEST_TIME"]=> 
string(10) "1504940730" } 
```

**Comment by NchemIcaLS** [comment]
I got it working! After hours of trying around with the plugin and NGINX, i finally decided to read more about the Shibboleth configuration. I assumed this couldn't be the problem because all the files and config were given to me by my Shibboleth Identity Provider and I was able to establish a session. I saw in a lot of example configurations that this RequestMapper element was needed and decided to add it to the shibboleth2.xml and boom it works! My Shibboleth IdP does not mention this anywhere in their instructions! So many hours wasted (been working on this for weeks)... sorry to take up your time on something so simple. You can close this issue.

```
<RequestMapper type="Native">
      <RequestMap applicationId="default">
          <Host name="example.com" authType="shibboleth" requireSession="false" >
              <Path name="secure" authType="shibboleth" requireSession="true"/>
          </Host>
      </RequestMap>
</RequestMapper>
```

**Comment by davidjb** [comment]
@NchemIcaLS The reason your IdP may not mention it is probably because they're assuming the use of Apache.  The `RequestMapper` element is needed for the Nginx/Shibboleth configuration as there's no "native" web server commands for nginx (eg like `ShibRequestSetting requireSession 1` in Apache).   There's more docs at https://github.com/nginx-shib/nginx-http-shibboleth/blob/master/CONFIG.rst#configuring-shibboleth-s-shibboleth2-xml-to-recognise-secured-paths.

**Comment by NchemIcaLS** [comment]
You are right. They assume I would use Apache. In hindsight it all makes sense and it's even written in your documentation! Being new to Shibboleth and custom NGINX modules, I had no idea what I had to do and decided not to edit the shibboleth2.xml given to me by the IdP.

**Comment by michaelryanmcneill** [comment]
Excellent news, glad to hear that you've got it fixed!

**Comment by videoman** [comment]
Wow, just spent hours on this - only to add the config to to the XML file and finally got it working.

**Comment by davidjb** [comment]
@videoman PRs and suggestions are welcome to help improve the documentation.
